name: 'TBtracker'
channels:
    - conda-forge
    - defaults
dependencies:
    - ipykernel
    - altair
    - altair-all
    - dash
    - dash-bootstrap-components
    - plotly
    - pip
    - pip:
        - geopandas
        - dash-vega-components
        - pyarrow
    - vega_datasets